feat(release): build

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -1,14 +1,17 @@
 ---
-name: build
+name: main
 
-on: [push, pull_request]
+on:
+  push:
+    branches: [main]
+  pull_request:
+    branches: [main]
 
 jobs:
-  build:
+  test:
     runs-on: ubuntu-latest
-    timeout-minutes: 10
     concurrency:
-      group: ci-${{ github.ref }}
+      group: ci-main-tests-${{ github.ref }}
       cancel-in-progress: true
 
     defaults:
@@ -16,21 +19,23 @@ jobs:
         shell: bash -l {0}
 
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
 
-      - uses: conda-incubator/setup-miniconda@v2
+      - uses: conda-incubator/setup-miniconda@v3
         with:
-          miniconda-version: "latest"
-          mamba-version: "1.*"
+          miniforge-version: latest
           environment-file: conda/dev.yaml
           channels: conda-forge,nodefaults
-          channel-priority: true
           activate-environment: pydeepsar
-          use-mamba: true
-          miniforge-variant: Mambaforge
+          auto-update-conda: true
+          conda-solver: libmamba
+
+      - name: Check poetry.lock
+        run: poetry check
 
       - name: Install dependencies
         run: |
+          poetry config virtualenvs.create false
           poetry install
 
       - name: Run tests
@@ -41,3 +46,34 @@ jobs:
         run: |
           pre-commit install
           makim tests.linter
+
+      # - name: Semantic Release PR Title Check
+      #   uses: osl-incubator/semantic-release-pr-title-check@v1.4.3
+      #   if: success() || failure()
+      #   with:
+      #     convention-name: conventionalcommits
+
+  # smoke-test:
+  #   runs-on: ubuntu-latest
+  #   concurrency:
+  #     group: ci-main-smoke-${{ matrix.smoke_file }}-${{ github.ref }}
+  #     cancel-in-progress: true
+
+  #   defaults:
+  #     run:
+  #       shell: bash -l {0}
+
+  #   steps:
+  #     - uses: actions/checkout@v4
+
+  #     - uses: conda-incubator/setup-miniconda@v3
+  #       with:
+  #         miniforge-version: latest
+  #         environment-file: conda/dev.yaml
+  #         channels: conda-forge,nodefaults
+  #         activate-environment: pydeepsar
+  #         auto-update-conda: true
+  #         conda-solver: libmamba
+
+  #     - name: Install dependencies
+  #       run: poetry install
